In [33]:
# BT1 - Tìm svd của một ma trận

# 1. Khai báo thư viện cần dùng: scipy.linalg
import numpy as np
from scipy.linalg import svd

# 2. Nhập ma trận A
A = np.array([[1, 0, 0, 0, 2],
              [0, 0, 3, 0, 0],
              [0, 0, 0, 0, 0],
              [0, 2, 0, 0, 0]])

# 3. Dùng hàm svd lên ma trận A để tính ma trận U, vector S_diag và V_trans
U, S_diag, V_trans = svd(A)

# 4. Tạo ra ma trận Σ từ vector S_diag
## 4.1 Tạo ma trận không cấp k × k
k = min(A.shape[0], A.shape[1])
Sigma_small = np.zeros((k, k))

## 4.2 Thay đường chéo của ma trận không bằng các phần tử của S_diag
np.fill_diagonal(Sigma_small, S_diag)

## 4.3 Thêm hàng/cột 0 vào Σ để cùng dạng với ma trận A ban đầu
Sigma_padded = np.pad(Sigma_small, ((0, A.shape[0] - k), (0, A.shape[1] - k)), mode='constant')

# 5. Xuất kết quả
print("* BT1\nMa trận A:")
print(A)

print("\nMa trận U:")
print(U)

print("\nMa trận V^T:")
print(V_trans)

print("\nMa trận Σ:")
print(Sigma_padded)

* BT1
Ma trận A:
[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 2 0 0 0]]

Ma trận U:
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]]

Ma trận V^T:
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [ 0.         -1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]

Ma trận Σ:
[[3.         0.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.         0.        ]
 [0.         0.         2.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [47]:
# BT2 - Tìm compact SVD của một ma trận

# 1. Tìm svd của ma trận A
import numpy as np
from scipy.linalg import svd

A = np.array([[1, 0, 0, 0, 2],
              [0, 0, 3, 0, 0],
              [0, 0, 0, 0, 0],
              [0, 2, 0, 0, 0]])

U, S_diag, V_trans = svd(A)

# 2. Tìm số giá trị λ khác 0 của ma trận A, đặt là r
r = np.sum(S_diag != 0)

# 3. Giữ lại r hàng và r cột đầu tiên của ma trận Σ để tạo thành Σ_r
k = min(A.shape[0], A.shape[1])
Sigma_small = np.zeros((k, k))
np.fill_diagonal(Sigma_small, S_diag)
Sigma_padded = np.pad(Sigma_small, ((0, A.shape[0] - k), (0, A.shape[1] - k)), mode='constant')

Sigma_r = Sigma_padded[:r, :r]

# 4. Giữ lại r cột đầu tiên của ma trận U để tạo ra U_r
U_r = U[:, :r]

# 5. Giữ lại r hàng đầu tiên của ma trận V để tạo ra V_r
V_r_trans = V_trans[:r, :]

# 6. Xuất kết quả
print("* BT2\nMa trận A:")
print(A)

print("\nMa trận U_r:")
print(U_r)

print("\nMa trận V_r^T:")
print(V_r_trans)

print("\nMa trận Σ_r:")
print(Sigma_r)

# Thử nhân lại U_r @ Sigma_r @ V_r_trans
A_new = U_r @ Sigma_r @ V_r_trans
print("\nMa trận A_new = U_r @ Sigma_r @ V_r_trans")
print(A_new)

* BT2
Ma trận A:
[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 2 0 0 0]]

Ma trận U_r:
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]]

Ma trận V_r^T:
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [ 0.         -1.          0.          0.          0.        ]]

Ma trận Σ_r:
[[3.         0.         0.        ]
 [0.         2.23606798 0.        ]
 [0.         0.         2.        ]]

Ma trận A_new = U_r @ Sigma_r @ V_r_trans
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]


In [62]:
# BT3 - Tìm truncated SVD khi biết số λ cần giữ lại

# 1. Tìm SVD của ma trận A như bài tập 1
import numpy as np
from scipy.linalg import svd

A = np.array([[1.01, 0.9, 0.2, 1.001, 0.3],
              [0.2, 1.01, 0.3, 0.8, 0.4],
              [1, 1.002, 2, 0.98, 2],
              [0.3, 2, 0.4, 1.01, 0.9],
              [1.1, 0.2, 0.03, 2, 0.87]])

U, S_diag, V_trans = svd(A)

# 2. Giữ lại 4 hàng, 4 cột đầu tiên của ma trận Σ để tạo ra ma trận Σ_k
k = 4
Sigma_small = np.zeros((k, k))
np.fill_diagonal(Sigma_small, S_diag[:k])
Sigma_k = Sigma_small

# 3. Giữ lại 4 cột đầu tiên của ma trận U để tạo ra U_k
U_k = U[:, :k]

# 4. Giữ lại 4 hàng đầu tiên của ma trận V^T để tạo ra V_k_trans
V_k_trans = V_trans[:k, :]

# 5. Áp dụng công thức để tính phần trăm lượng thông tin được giữ lại lúc này
numerator = np.sum(S_diag[k:]**2)
denominator = np.sum(S_diag**2)
information_retained = 1 - (numerator / denominator)

A_k = U_k @ Sigma_k @ V_k_trans
# Định dạng các phần tử của ma trận khi in ra
np.set_printoptions(precision=3, suppress=True)

# 6. Xuất kết quả
print("* BT3\nMa trận gốc A:")
print(A)
print("\nMa trận U_k:")
print(U_k)
print("\nMa trận V_k^T:")
print(V_k_trans)
print("\nMa trận Σ_k:")
print(Sigma_k)
print("\nMa trận xấp xỉ A_k = U_k @ Sigma_k @ V_k_trans")
print(A_k)
print("\nLượng thông tin còn giữ lại:")
print(information_retained)

* BT3
Ma trận gốc A:
[[1.01  0.9   0.2   1.001 0.3  ]
 [0.2   1.01  0.3   0.8   0.4  ]
 [1.    1.002 2.    0.98  2.   ]
 [0.3   2.    0.4   1.01  0.9  ]
 [1.1   0.2   0.03  2.    0.87 ]]

Ma trận U_k:
[[-0.328  0.329  0.088 -0.881]
 [-0.274  0.091  0.315  0.161]
 [-0.648 -0.659 -0.38  -0.043]
 [-0.466  0.021  0.719  0.256]
 [-0.424  0.67  -0.481  0.361]]

Ma trận V_k^T:
[[-0.35  -0.478 -0.351 -0.534 -0.49 ]
 [ 0.243 -0.054 -0.667  0.623 -0.324]
 [-0.343  0.86  -0.237 -0.17  -0.239]
 [-0.776 -0.161 -0.182  0.339  0.473]]

Ma trận Σ_k:
[[4.682 0.    0.    0.   ]
 [0.    1.793 0.    0.   ]
 [0.    0.    1.58  0.   ]
 [0.    0.    0.    0.549]]

Ma trận xấp xỉ A_k = U_k @ Sigma_k @ V_k_trans
[[1.01  0.9   0.201 1.002 0.299]
 [0.25  1.018 0.207 0.732 0.497]
 [1.001 1.002 1.999 0.979 2.001]
 [0.275 1.996 0.447 1.044 0.851]
 [1.095 0.199 0.04  2.007 0.86 ]]

Lượng thông tin còn giữ lại:
0.9988593923179663


In [85]:
# BT4 - Tìm truncated SVD khi biết phần trăm lượng thông tin muốn giữ

# 1. Tìm SVD của ma trận A như bài tập 1
import numpy as np
from scipy.linalg import svd

A = np.array([[1.01, 0.9, 0.2, 1.001, 0.3],
              [0.2, 1.01, 0.3, 0.8, 0.4],
              [1, 1.002, 2, 0.98, 2],
              [0.3, 2, 0.4, 1.01, 0.9],
              [1.1, 0.2, 0.03, 2, 0.87]])

U, S_diag, V_trans = svd(A)

# 2. Áp dụng công thức để tìm ra số kλ cần phải giữ
## Tính tổng bình phương của tất cả các giá trị riêng
total_variance = np.sum(S_diag**2)
## Tính tổng bình phương tích lũy của các giá trị riêng
cumulative_variance = np.cumsum(S_diag**2)
## Xác định giá trị I%
I_percentage = 0.9
## Khởi tạo tổng tích lũy và số lượng k
k = np.where(cumulative_variance / total_variance >= I_percentage)[0][0] + 1

# 3. Giữ lại k hàng, k cột đầu tiên của ma trận Σ để tạo ra ma trận Σ_k
Sigma_small = np.zeros((k, k))
np.fill_diagonal(Sigma_small, S_diag[:k])
Sigma_k = Sigma_small

# 4. Giữ lại k cột đầu tiên của ma trận U để tạo ra U_k
U_k = U[:, :k]

# 5. Giữ lại k hàng đầu tiên của ma trận V^T để tạo ra V_k^T
V_k_trans = V_trans[:k, :]

# 6. Xuất kết quả
print("* BT4\nMa trận gốc A:")
print(A)
print("\nMa trận U_k:")
print(U_k)
print("\nMa trận V_k^T:")
print(V_k_trans)
print("\nMa trận Σ_k:")
print(Sigma_k)
print("\nLượng thông tin cần giữ ít nhất:")
print(I_percentage)
print(f"\nSố kλ cần giữ khi muốn giữ lại ít nhất {I_percentage} lượng thông tin ban đầu:")
print(k)

* BT4
Ma trận gốc A:
[[1.01  0.9   0.2   1.001 0.3  ]
 [0.2   1.01  0.3   0.8   0.4  ]
 [1.    1.002 2.    0.98  2.   ]
 [0.3   2.    0.4   1.01  0.9  ]
 [1.1   0.2   0.03  2.    0.87 ]]

Ma trận U_k:
[[-0.328  0.329  0.088]
 [-0.274  0.091  0.315]
 [-0.648 -0.659 -0.38 ]
 [-0.466  0.021  0.719]
 [-0.424  0.67  -0.481]]

Ma trận V_k^T:
[[-0.35  -0.478 -0.351 -0.534 -0.49 ]
 [ 0.243 -0.054 -0.667  0.623 -0.324]
 [-0.343  0.86  -0.237 -0.17  -0.239]]

Ma trận Σ_k:
[[4.682 0.    0.   ]
 [0.    1.793 0.   ]
 [0.    0.    1.58 ]]

Lượng thông tin cần giữ ít nhất:
0.9

Số kλ cần giữ khi muốn giữ lại ít nhất 0.9 lượng thông tin ban đầu:
3
